name: MLOps Pipeline

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:

      # Step 1
      - uses: actions/checkout@v3

      # Step 3
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements_alternate.txt

      # Step 4
      - name: Train Model
        run: |
          python models.py
      
      # Step 5
      - name: Model metrics
        run: |
          echo "Model metrics" > report.md
          cat output.txt >> report.md

