name: MLOps Pipeline

on:
  push:
    branches:
      - main


jobs:
  Pipeline:
    runs-on: ubuntu-latest

    steps:

      # Step 1
      - uses: actions/checkout@v2

      # Step 2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      # Step 3
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4
      - name: Train Model
        run: |
          python models.py
      
      # Step 5
      - name: Model metrics
        run: |
          echo "Model metrics" > report.md
          cat output.txt >> report.md

